services:
  api:
    build:
      context: .  # Use the solution root as build context
      dockerfile: ./docker/build/api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./docker/certs:/etc/nginx/certs:ro
      - ./docker/data/api-data:/app/data
      - ./docker/data/api-keys:/root/.aspnet/DataProtection-Keys

  app:
    build:
      context: ./ # Use the solution root as build context
      dockerfile: ./docker/build/app/Dockerfile
    ports:
      - "4200:443"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
      - ./docker/certs:/etc/nginx/certs:ro
    depends_on:
      - api

networks:
  default:
    driver: bridge
