version: '3.8'
services:
  dotnet-api:
    build:
      context: .  # Use the solution root as build context
      dockerfile: ./docker/build/api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./docker/deploy/api:/app

  angular-app:
    build:
      context: ./ # Use the solution root as build context
      dockerfile: ./docker/build/app/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    depends_on:
      - dotnet-api

networks:
  default:
    driver: bridge
